baseURL = "https://dragonbrick.vercel.app/"
dataDir = "data"
languageCode = "en-us"
title = "Dragonbrick"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  homepage_features = true
  homepage_services = true
  google_analytics_id=""
  favicon = "favicon.png"

  [params.logo]
    mobile = "dragon.jpg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "dragon.jpg"
    desktop_height = "80px"
    desktop_width = "auto"
    alt = "Dragon Brick logo"

  [params.homepage_meta_tags]
    meta_description = "Dragon Brick - Chuyên đồ chơi LEGO chính hãng, Chất lượng tốt nhất 'earth 616'"
    meta_og_title = "Dragon Brick - Ghép đam mê, xây giấc mơ"
    meta_og_type = "website"
    meta_og_url = "https://dragonbrick.vercel.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Dịch vụ order"
	url = "/Dich-vu-order/"
    weight = 1

[[menu.main]]
    name = "Cửa hàng"
    url = "/Cua-hang/"
    weight = 2

[[menu.main]]
    name = "Danh mục"
    url = "/danh-muc/"
    weight = 3

[[menu.main]]
    name = "Về Dragon Brick"
    url = "/Ve-Dragon-Brick/"
    weight = 3

[[menu.main]]
    name = "Liên hệ"
    url = "/Lien-he/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
# update menu